### ISSUE TITLE
Firefox version 47.0 crashing while opening through selenium web driver

### ISSUE THREAD

**Issue by pulakpattanayak** [SeleniumHQ/www.seleniumhq.org#92] opened 2016-06-08 15:11 UTC
Steps to reproduce:

I am trying to run a simple script using selenium and Firefox web driver.
Please find the details:
Platform : Windows
Python Version: Python 2.7.11
selenium module version : 2.53.2

Issue:
While opening the browser it is crashing and showing ''Firefox has stopped working"

Code:
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("https://www.google.com")

**Comment by lukeis** [comment] 2016-06-08 15:38
don't log selenium bugs against the website, log them against the selenium project repo instead.

But this is a duplicate of https://github.com/SeleniumHQ/selenium/issues/2110

**Closed by lukeis** 2016-06-08 15:38 UTC

**Comment by pulakpattanayak** [comment] 2016-06-08 15:49
Thanks for the information..
