### ISSUE TITLE
500 Server Error when accessing WebDriver documentation

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/www.seleniumhq.org#155] opened 2017-07-04 03:22 UTC
Following http://www.seleniumhq.org/docs/03_webdriver.jsp gives an error:

```
Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

**Comment by juangj** [comment] 2017-07-05 21:53
(https://travis-ci.org/SeleniumHQ/www.seleniumhq.org/builds/248987501 is the log of the last Travis deployment)

**Comment by p0deje** [comment] 2017-07-06 04:50
I don't know how website works and can't find anything suspicious in logs :(

**Comment by juangj** [comment] 2017-07-06 20:02
Same, can't say I really know anything about how the website works. I wasn't able to reproduce the problem in the devserver, either (which makes sense -- my devserver would be built in the same environment as the one I deployed to App Engine).

**Comment by juangj** [comment] 2017-07-07 19:30
Should be fixed by 1f419bf7cafe0c3893d699d6b87802608ac6582c, though that doesn't explain why I couldn't reproduce locally.

**Closed by juangj** 2017-07-07 19:30 UTC
