### ISSUE TITLE
The selenium IDE doc has a lot of garbage showing up like â€“, â€™, â€œ.

### ISSUE THREAD

**Issue by TapaswiniR** [SeleniumHQ/www.seleniumhq.org#147] opened 2017-05-31 06:21 UTC
The Selenium doc at 'http://www.seleniumhq.org/docs/02_selenium_ide.jsp#alerts-popups-and-multiple-windows' displays a lot of garbage like â€“, â€™, â€œ. The UTF-8 characters are getting replaced by these characters, which makes it difficult to refer the document.

Refer to the image:
![selenium ide selenium documentation 1](https://cloud.githubusercontent.com/assets/29085986/26618274/5f66baa4-45f7-11e7-9a00-d36d3ba6e1e2.png)

**Comment by manoj9788** [comment] 2017-05-31 06:32
Duplicate of #144

**Closed by manoj9788** 2017-05-31 06:32 UTC
